# Generated by Django 5.0.6 on 2024-05-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_breed_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
